# Ficha de trabalho 1

Conteúdos:
* Utilização do package NumPy.
* Manipulação de matrizes e vetores.
* Conceitos básicos de algebra linear: matriz identidade, multiplicação de matrizes, inversa.

======================================================


1 - Considera o peso e altura referente a 12 pessoas. 
```python
alturas: [1.73, 1.89, 2.03, 1.61, 1.57, 1.90, 1.73, 1.65, 1.59, 1.65, 1.71, 1.68]
pesos: [89, 79, 110, 60, 51, 88, 68, 67, 56, 65, 85, 67]
```
Usando a classe ndarray do package NumPy, cria uma matriz  em que a primeira linha tenha a altura e a segunda os pesos associados a cada uma das pessoas.


In [1]:
import numpy as np
alturas = [1.73, 1.89, 2.03, 1.61, 1.57, 1.90, 1.73, 1.65, 1.59, 1.65, 1.71, 1.68]
pesos = [89, 79, 110, 60, 51, 88, 68, 67, 56, 65, 85, 67]

In [2]:
a = np.array(alturas)
p = np.array(pesos)

In [3]:
ap = np.vstack((a,p))
ap
# ou mat = np.array([alturas, pesos])

array([[  1.73,   1.89,   2.03,   1.61,   1.57,   1.9 ,   1.73,   1.65,
          1.59,   1.65,   1.71,   1.68],
       [ 89.  ,  79.  , 110.  ,  60.  ,  51.  ,  88.  ,  68.  ,  67.  ,
         56.  ,  65.  ,  85.  ,  67.  ]])

In [4]:
ap.shape = 2,12

2 - Quantas dimensões tem o array? Qual o tamanho de cada uma das dimensões?

In [5]:
print("ndim: ", ap.ndim)
print("shape: ", ap.shape)
print("size: ", ap.size)
print("dtype: ", ap.dtype)
print("itemsize: ", ap.itemsize)

print("O array tem 2 dimensões, cada uma com 12 elementos.")

ndim:  2
shape:  (2, 12)
size:  24
dtype:  float64
itemsize:  8
O array tem 2 dimensões, cada uma com 12 elementos.


3 - Com base na informação presente no objeto **mat**, calcula o IMC de cada uma das pessoas. (IMC = peso/altura^2) (operador de potência: ** )

In [6]:
mat = ap
print(mat[:1])
print(mat[[0]])
print(mat[0])
print(mat[1])
print('-------')
print(mat)

[[1.73 1.89 2.03 1.61 1.57 1.9  1.73 1.65 1.59 1.65 1.71 1.68]]
[[1.73 1.89 2.03 1.61 1.57 1.9  1.73 1.65 1.59 1.65 1.71 1.68]]
[1.73 1.89 2.03 1.61 1.57 1.9  1.73 1.65 1.59 1.65 1.71 1.68]
[ 89.  79. 110.  60.  51.  88.  68.  67.  56.  65.  85.  67.]
-------
[[  1.73   1.89   2.03   1.61   1.57   1.9    1.73   1.65   1.59   1.65
    1.71   1.68]
 [ 89.    79.   110.    60.    51.    88.    68.    67.    56.    65.
   85.    67.  ]]


In [7]:
imc = mat[1]/(mat[0]**2)
# imc = mat[1,:]/mat[0,:]**2

In [8]:
print('imc', imc)
print('size', imc.size)

imc [29.73704434 22.11584222 26.69319809 23.14725512 20.69049454 24.3767313
 22.72043837 24.6097337  22.15102251 23.87511478 29.0687733  23.73866213]
size 12


4 - Sabendo que pessoas com IMC acima de 25 têm excesso de peso, quantas pessoas estão numa situação de excesso de peso?

In [9]:
imc2 = imc[imc>25]
imc2

array([29.73704434, 26.69319809, 29.0687733 ])

In [10]:
#outras hipóteses
len(imc[imc>25])
sum(imc>25)

3

5 - Constroi um novo array com base no anterior, onde a primeira coluna contenha a altura, a segunda o peso e a terceira o IMC.

In [11]:
mat2 = np.column_stack((mat.transpose(), imc))
mat2.shape

(12, 3)

In [12]:
mat2

array([[  1.73      ,  89.        ,  29.73704434],
       [  1.89      ,  79.        ,  22.11584222],
       [  2.03      , 110.        ,  26.69319809],
       [  1.61      ,  60.        ,  23.14725512],
       [  1.57      ,  51.        ,  20.69049454],
       [  1.9       ,  88.        ,  24.3767313 ],
       [  1.73      ,  68.        ,  22.72043837],
       [  1.65      ,  67.        ,  24.6097337 ],
       [  1.59      ,  56.        ,  22.15102251],
       [  1.65      ,  65.        ,  23.87511478],
       [  1.71      ,  85.        ,  29.0687733 ],
       [  1.68      ,  67.        ,  23.73866213]])

6 - Calcula o valor máximo, mínimo e o valor médio do IMC.

In [13]:
print(np.max(mat2[:,2]))
print(mat2[:,2].min())
print(np.mean(mat2, axis=0)[2]) # ir buscar o terceiro valor que estamos à procura

29.737044338267232
20.690494543389182
24.410359200529246


7 - Cria uma matriz 2x3 com valores aleatórios, e outra matrix 3x2 com valores pares sequenciais de 2 até 12, inclusivé.

In [14]:
from numpy.random import *
r1 = rand(2,3) #matriz 2*3 com valores aleatórios
r1

array([[0.24055823, 0.72880081, 0.03572637],
       [0.21647899, 0.87860199, 0.78129863]])

In [15]:
np.arange(2,14,2) #semelhante ao range

array([ 2,  4,  6,  8, 10, 12])

8 - Calcula a multiplicação das duas matrizes e guarda o resultado numa variável designada por *mul*.

In [16]:
a = np.array([[1,2],[3,4]])
b = np.array([[-1,3],[4,2]])
print('Matriz a: \n',a)
print('Matriz b: \n',b)
print('Dot product a.b:')
mul = np.dot(a,b)
print(mul)
print('***Multiplicação elemento a elemento***')
mul2 = a * b
print(mul2)

Matriz a: 
 [[1 2]
 [3 4]]
Matriz b: 
 [[-1  3]
 [ 4  2]]
Dot product a.b:
[[ 7  7]
 [13 17]]
***Multiplicação elemento a elemento***
[[-1  6]
 [12  8]]


9 - Cria a matriz identidade de tamanho 2. (explora as funções numpy.eye e numpy.identity)

In [17]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [18]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

10 - Qual a diferença entre usar o operador \* ou a função *dot* na multiplicação da matriz *mul* pela matriz identidade.

In [19]:
mul*np.identity(2)

array([[ 7.,  0.],
       [ 0., 17.]])

In [20]:
np.dot(mul,np.identity(2))

array([[ 7.,  7.],
       [13., 17.]])

Enquanto que * faz a multiplicação elemento a elemento, já com o dot é feito o produto das matrizes, resultando na matriz mul. 

11 - Calcula a inversa da matriz *mul*. (Explora o módulo para algebra linear *np.linalg*)

$A.A^{-1} = I$

Uma matriz só tem inversa se o seu determinante for diferente de zero. Caso o determinante det(B) seja igual a zero, a matriz não possui inversa.

In [21]:
np.linalg.det(mul) # o determinante é diferente de zero, por isso, tem inversa

27.999999999999996

In [22]:
mul_inv = np.linalg.inv(mul)
mul_inv

array([[ 0.60714286, -0.25      ],
       [-0.46428571,  0.25      ]])

In [23]:
np.dot(mul,mul_inv)

array([[1., 0.],
       [0., 1.]])

In [24]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [25]:
np.dot(mul,mul_inv) == np.identity(2)

array([[ True,  True],
       [ True,  True]])

12 - O que obtens se multiplicares a matriz mul pela sua inversa?